version: "3.1"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - todonetwork
  server:
    image: node:10
    restart: always
    ports:
      - 3000:3000
    links:
      - mongodb
    networks:
      - todonetwork
  web:
    image: node:10
    restart: always
    ports:
      - 80:80
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - server
    networks:
      - todonetwork
networks:
  todonetwork:
    driver: bridge
